version: '3.7'

volumes:
  pg_auth_data:
    name: pg_auth_data

services:

  api:
    container_name: auth_api_service
    build:
      context: app
      dockerfile: settings/docker/fastapi/dockerfile
    ports:
      - "8001:8001"
      - "5679:5679"
    env_file:
      app/.env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s
    depends_on:
      - redis
      - postgres
    volumes:
      - ./app/src/:/opt/app/src
    entrypoint:
      [
        "sh",
        "-c",
        "pip install debugpy && python -m debugpy --listen 0.0.0.0:5679 -m uvicorn src.main:app --reload --host 0.0.0.0 --port 8001",
      ]

  redis:
    container_name: auth_redis_cache
    build:
      context: app
      dockerfile: settings/docker/redis/dockerfile
    env_file:
      app/.env
    expose:
      - "6379"

  postgres:
    container_name: auth_postgres
    build:
      context: app/settings/docker/postgres
      dockerfile: dockerfile
    volumes:
      - pg_auth_data:/var/lib/postgresql/data/
    env_file:
      app/.env
    expose:
      - "5432"

networks:
  default:
      name: auth_network